apiVersion: ecommerce.io/v1
kind: API
metadata:
  name: Ecommerce-api
  description: Ecommerce API Rest
  tags:
    - api
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: group:backstage_admin
